import { useEffect, useRef, useState } from 'react';
import { adminOperationsRequest } from '@paperbanana/api';
import { useAdminData, errorText } from './adminApi';
import { Badge, Facts, History, Identity, State } from './AdminCommon';
import { date, duration, label, OPEN_REVIEW } from './adminState';

function DetailHeader({ title, id, back, refresh }) {
  return <header className="ops-detail-head"><div><button className="ops-link" onClick={back}>← 返回列表</button><h2 tabIndex={-1}>{title}</h2><code>{id}</code></div><button onClick={refresh}>刷新详情</button></header>;
}
function Mutation({ apiBase, entity, type, onSaved }) {
  const [prompt, setPrompt] = useState(entity.prompt || ''), [capability, setCapability] = useState(entity.capability || '');
  const [notes, setNotes] = useState(''), [followup, setFollowup] = useState(entity.followup || 'followup');
  const [confirm, setConfirm] = useState(null), [busy, setBusy] = useState(false), [error, setError] = useState(null), [message, setMessage] = useState('');
  const alive = useRef(true);
  useEffect(() => { alive.current = true; return () => { alive.current = false; }; }, []);
  const submit = async () => {
    const choice = confirm; setBusy(true); setError(null); setMessage('');
    try {
      const payload = type === 'task' ? { id: entity.id, followup, notes } : { submissionId: entity.submissionId, editedPrompt: prompt, editedCapability: capability, decisionNotes: notes, ...(choice !== 'edit' ? { decision: choice } : {}) };
      await adminOperationsRequest(apiBase, type === 'task' ? 'adminTaskFollowup' : choice === 'edit' ? 'adminCommunityEdit' : 'adminBenchmarkPromptDecision', { ...payload, expectedRevision: entity.revision });
      if (alive.current) { setConfirm(null); setNotes(''); setMessage('已保存，处理记录与状态已更新。'); onSaved(); }
    } catch (error) { if (alive.current) { setError(error); setConfirm(null); } }
    finally { if (alive.current) setBusy(false); }
  };
  if (type === 'community' && !OPEN_REVIEW.includes(entity.status)) return <div className="ops-notice">该提交已完成审核，保留原稿与审核记录。当前正式题集和评估结果不受此操作影响。</div>;
  return <section className="ops-card"><h3>{type === 'task' ? '运营跟进' : '编辑与审核'}</h3><p className="ops-muted">{type === 'task' ? '仅修改跟进状态并记录说明，不会取消、重试或改变任务执行结果。' : '编辑保留原始提交；审核通过进入下期候选，不会自动发布，也不会改动已有评估结果。'}</p>
    <fieldset disabled={busy || Boolean(confirm)}>
      {type === 'task' ? <label>跟进状态<select aria-label="跟进状态" value={followup} onChange={(e) => setFollowup(e.target.value)}>{['unreviewed', 'followup', 'resolved'].map((v) => <option key={v} value={v}>{label(v)}</option>)}</select></label> : <><label>能力分类<input aria-label="能力分类" maxLength={1000} value={capability} onChange={(e) => setCapability(e.target.value)} /></label><label>题目内容<textarea aria-label="题目内容" rows={7} maxLength={4000} value={prompt} onChange={(e) => setPrompt(e.target.value)} /></label></>}
      <label>处理说明<textarea aria-label="处理说明" rows={3} maxLength={1000} value={notes} onChange={(e) => setNotes(e.target.value)} placeholder={type === 'task' ? '记录已检查的问题、处理结果或下一步' : '说明修改、通过、合并或拒绝的依据；合并请写明目标候选'} required /></label>
      <div className="ops-actions">{type === 'task' ? <button disabled={!notes.trim()} onClick={() => setConfirm('followup')}>保存跟进记录</button> : <><button disabled={!notes.trim() || !prompt.trim()} onClick={() => setConfirm('edit')}>保存编辑</button><button className="ops-primary" disabled={!notes.trim() || !prompt.trim()} onClick={() => setConfirm('approved_for_next_suite')}>通过为下期候选</button><button disabled={!notes.trim() || !prompt.trim()} onClick={() => setConfirm('merged')}>标记已合并</button><button className="ops-danger" disabled={!notes.trim() || !prompt.trim()} onClick={() => setConfirm('rejected')}>拒绝</button></>}</div>
    </fieldset>
    {confirm && <div className="ops-confirm" role="alertdialog" aria-label="确认管理操作"><strong>{confirm === 'edit' ? '确认保存编辑' : type === 'task' ? `确认标记为${label(followup)}` : `确认${label(confirm)}`}</strong><p>影响范围：仅当前{type === 'task' ? '任务的运营跟进记录。' : '一条社区提交。审核完成后不能在此撤回或再次编辑。'}</p><blockquote>{notes}</blockquote><div className="ops-actions"><button className="ops-primary" disabled={busy} onClick={submit}>{busy ? '正在保存…' : '确认保存'}</button><button disabled={busy} onClick={() => setConfirm(null)}>继续检查</button></div></div>}
    {error && <div role="alert" className="ops-error"><p>{errorText(error)}</p>{error.code === 409 && <button onClick={() => { setError(null); onSaved(); }}>刷新记录后核对草稿</button>}</div>}{message && <p role="status" className="ops-success">{message}</p>}
  </section>;
}
function Related({ apiBase, userId, go, refresh, reveal }) {
  const jobs = useAdminData(apiBase, 'adminTaskList', { userId, pageSize: 10 }, refresh);
  const community = useAdminData(apiBase, 'adminCommunityList', { userId, pageSize: 10 }, refresh);
  const feedback = useAdminData(apiBase, 'adminFeedbackList', { userId, pageSize: 10, revealContact: reveal }, refresh);
  return <div className="ops-related">{[['jobs', '关联任务', jobs], ['community', '社区提交', community], ['feedback', '反馈与联系方式', feedback]].map(([section, title, result]) => <section key={section} className="ops-card"><div className="ops-card-head"><h3>{title}</h3><button className="ops-link" onClick={() => go(section, { userId })}>查看全部{result.data ? `（${result.data.pagination.total}）` : ''} →</button></div><State {...result}>{result.data?.rows.length ? <ul className="ops-related-list">{result.data.rows.map((r) => <li key={r.id || r.submissionId}>{section === 'feedback' ? <><p>{r.message}</p><small>联系方式（反馈自填，未验证）：{r.contact || '未提供'} · {date(r.createdAt)}</small></> : <><button className="ops-link" onClick={() => go(section, { userId, id: r.id || r.submissionId })}>{r.title || r.prompt}</button><div><Badge value={r.status} /><small>{date(r.createdAt)}</small></div></>}</li>)}</ul> : <p className="ops-muted">暂无关联记录。</p>}</State></section>)}</div>;
}
export function UserDetail({ apiBase, id, back, go }) {
  const [refresh, setRefresh] = useState(0), [reveal, setReveal] = useState(false);
  const result = useAdminData(apiBase, 'adminUserDetail', { id, revealContact: reveal }, refresh), user = result.data?.user;
  return <><DetailHeader title="用户详情" id={id} back={back} refresh={() => setRefresh((n) => n + 1)} /><State {...result} retry={() => setRefresh((n) => n + 1)}>{user && <><section className="ops-card"><div className="ops-card-head"><h3>{user.name || '未设置昵称'} <Badge value={user.status}>{user.status === 'pending' ? '注销处理中' : label(user.status)}</Badge></h3><button onClick={() => setReveal((v) => !v)}>{reveal ? '隐藏联系方式' : '查看完整邮箱与反馈联系方式'}</button></div><Facts items={[
    ['用户 ID', <code>{user.id}</code>], ['邮箱', user.email], ['邮箱验证', <Badge value={user.emailVerified ? 'verified' : 'unverified'} />], ['已有登录方式', user.loginMethods.length ? user.loginMethods.map(label).join('、') : '未记录登录方式'], ['注册时间', date(user.createdAt)], ['资料更新时间', date(user.updatedAt)], ['最近保留的登录记录', date(user.latestRetainedLoginAt)], ['当前有效会话数', String(user.activeSessions)],
  ]} /><p className="ops-muted">同一用户 ID 关联登录方式和业务记录；联系方式来自反馈时未经身份验证。登录时间取仍保留的会话创建时间，过期会话清理后不代表完整登录历史。</p>{user.deletion && <div className="ops-notice">注销阶段：{user.deletion.phase}；最近更新：{date(user.deletion.updatedAt)}。{user.deletion.lastErrorCode}</div>}</section><Related apiBase={apiBase} userId={id} go={go} refresh={refresh} reveal={reveal} /></>}</State>{result.error?.code === 404 && <div className="ops-actions"><button onClick={() => go('jobs', { userId: id })}>按原用户 ID 查询任务</button><button onClick={() => go('community', { userId: id })}>按原用户 ID 查询社区提交</button></div>}</>;
}
export function TaskDetail({ apiBase, id, back, go }) {
  const [refresh, setRefresh] = useState(0), result = useAdminData(apiBase, 'adminTaskDetail', { id }, refresh), task = result.data?.task;
  return <><DetailHeader title="任务详情" id={id} back={back} refresh={() => setRefresh((n) => n + 1)} /><State {...result} retry={() => setRefresh((n) => n + 1)}>{task && <><section className="ops-card"><h3>{task.title}</h3><Facts items={[
    ['任务归属', <Identity id={task.userId} email={task.email} go={go} />], ['执行状态', <Badge value={task.status} />], ['任务类型', label(task.type)], ['运营跟进', <Badge value={task.followup} />], ['创建时间', date(task.createdAt)], ['开始时间', date(task.startedAt)], ['完成时间', date(task.completedAt)], ['执行耗时', duration(task.durationMs)], ['主模型', task.models.main], ['图像模型', task.models.image], ['识图模型', task.models.vision],
  ]} /></section>{task.error && <section className="ops-card ops-error"><h3>失败原因{task.errorCode ? ` · ${task.errorCode}` : ''}</h3><p className="ops-pre">{task.error}</p></section>}<section className="ops-card"><h3>输入与结果</h3><details open><summary>输入内容</summary><h4>方法内容</h4><p className="ops-pre">{task.methodContent || '未记录'}</p><h4>图注</h4><p className="ops-pre">{task.caption || '未记录'}</p><h4>负向提示词</h4><p className="ops-pre">{task.negativePrompt || '未提供'}</p></details><h4>生成结果</h4>{task.results.length ? <div className="ops-images">{task.results.map((image, i) => <figure key={`${image.url}-${i}`}><a href={image.url} target="_blank" rel="noreferrer"><img src={image.url} alt={`生成结果 ${i + 1}`} loading="lazy" /></a><figcaption><a href={image.url} target="_blank" rel="noreferrer">打开结果 {i + 1}</a></figcaption></figure>)}</div> : <p className="ops-muted">{['reserved', 'queued', 'running'].includes(task.status) ? '任务尚未产出结果。' : '该任务没有可展示的生成结果。'}</p>}{task.results.length > 0 && <p className="ops-muted">结果链接有有效期，失效后可刷新详情重新获取。</p>}{task.references.length > 0 && <details><summary>参考图（{task.references.length}）</summary><div className="ops-images">{task.references.map((image, i) => <img key={i} src={image.url} alt={`参考图 ${i + 1}`} loading="lazy" />)}</div></details>}</section><section className="ops-card"><h3>执行记录</h3>{task.stages.length ? task.stages.map((s, i) => <details key={i}><summary>{s.title || s.type || `阶段 ${i + 1}`}</summary><p className="ops-pre">{s.text || '没有文字记录'}</p>{s.error && <p className="ops-error">{s.error}</p>}{s.image?.url && <img className="ops-stage-image" src={s.image.url} alt={s.title || `阶段 ${i + 1}`} />}</details>) : <p className="ops-muted">没有阶段记录。</p>}<details><summary>最近日志（最多 200 条）</summary><pre>{task.logs.join('\n') || '暂无日志'}</pre></details></section><Mutation apiBase={apiBase} entity={task} type="task" onSaved={() => setRefresh((n) => n + 1)} /><History entries={task.history} /></>}</State></>;
}
export function CommunityDetail({ apiBase, id, back, go }) {
  const [refresh, setRefresh] = useState(0), result = useAdminData(apiBase, 'adminCommunityDetail', { id }, refresh), row = result.data?.submission;
  return <><DetailHeader title="社区评估题详情" id={id} back={back} refresh={() => setRefresh((n) => n + 1)} /><State {...result} retry={() => setRefresh((n) => n + 1)}>{row && <><section className="ops-card"><Facts items={[
    ['审核状态', <Badge value={row.status} />], ['提交者', <Identity id={row.userId} go={go} />], ['来源', '用户社区提交'], ['能力分类', row.capability], ['提交时间', date(row.createdAt)], ['最近更新时间', date(row.updatedAt)],
  ]} /><h3>当前题目内容</h3><p className="ops-pre">{row.prompt}</p><Facts items={[['必须项', row.requiredElements || '未提供'], ['禁止项', row.forbiddenResults || '未提供'], ['提交备注', row.notes || '未提供']]} /><details><summary>查看原始提交</summary><p>原始分类：{row.originalCapability || '未提供'}</p><p className="ops-pre">{row.originalPrompt}</p></details></section><section className="ops-card"><h3>关联候选与评估</h3><p className="ops-notice">审核通过仅表示进入下期候选。当前系统尚未保存社区提交与正式题集、已发布评估结果的可靠关联，因此这里不标记“已发布”。</p>{row.digests.length ? row.digests.map((d) => <details key={d.id}><summary>归组批次 {d.id} · {date(d.createdAt)}</summary>{d.candidates.map((c) => <div key={c.id}><h4>{c.id}</h4><p>{c.capability}</p><p className="ops-pre">{c.prompt}</p><p>合并依据：{c.mergeReason || '未记录'}</p></div>)}</details>) : <p className="ops-muted">尚无关联归组候选。</p>}{row.digestHasMore && <p>这里只展示最近 20 个归组批次。</p>}</section><Mutation apiBase={apiBase} entity={row} type="community" onSaved={() => setRefresh((n) => n + 1)} /><History entries={row.history} legacy={row.decidedAt && !row.history.length ? `${date(row.decidedAt)} · ${row.decidedBy || '处理人未记录'} · ${row.decisionNotes || '无处理说明'}` : ''} /></>}</State></>;
}
