import { useEffect, useRef, useState } from 'react';
import { Activity, ArrowUpRight, LayoutDashboard, RefreshCcw, Search, ShieldCheck, Users } from 'lucide-react';
import BenchmarkAdminPanel from '../BenchmarkAdminPanel';
import { useAdminData } from './adminApi';
import { Badge, Identity, Pager, State } from './AdminCommon';
import { CommunityDetail, TaskDetail, UserDetail } from './AdminDetails';
import { adminUrl, date, duration, JOB_STATES, label, queryFor, rangeDates, readAdminLocation, REVIEW_STATES, SECTIONS } from './adminState';

const ACTIONS = { users: 'adminUserList', jobs: 'adminTaskList', community: 'adminCommunityList', feedback: 'adminFeedbackList' };
const HEADERS = { users: ['账号', '登录方式', '验证 / 状态', '注册时间', '最近保留登录', '有效会话'], jobs: ['任务', '归属', '状态 / 跟进', '类型 / 模型', '创建时间', '完成耗时'], community: ['题目内容', '提交者', '分类', '审核状态', '提交时间'], feedback: ['反馈内容', '提交者', '联系方式', '关联任务', '状态 / 时间'] };
const SEARCH_HINTS = { users: '完整用户 ID、邮箱或昵称', jobs: '任务 ID、名称、图注、用户 ID 或邮箱', community: '题目、提交 ID、用户 ID、分类或归组批次', feedback: '反馈内容、联系方式、用户 ID 或关联任务' };

function stateAccountLabel(field, value, section) { return section === 'users' && field === 'status' && value === 'pending' ? '注销处理中' : label(value); }
function SelectFilter({ title, field, values, draft, update }) {
  return <label>{title}<select aria-label={title} value={draft[field] || ''} onChange={(e) => update(field, e.target.value)}><option value="">全部</option>{values.map((v) => <option value={v} key={v}>{stateAccountLabel(field, v, draft.section)}</option>)}</select></label>;
}
function Filters({ state, change }) {
  const [draft, setDraft] = useState(state);
  useEffect(() => { setDraft(state); }, [state]);
  const update = (key, value) => setDraft((d) => ({ ...d, [key]: value }));
  return <form className="ops-filters" onSubmit={(e) => { e.preventDefault(); change({ ...draft, page: 1, id: '' }); }}>
    <div className="ops-filter-row"><label className="ops-search"><span><Search size={14} />搜索</span><input aria-label="搜索" name="search" maxLength={120} value={draft.q || ''} onChange={(e) => update('q', e.target.value)} placeholder={state.section === 'users' && draft.searchBy === 'contact' ? '反馈中实际填写的联系方式，至少 3 个字符' : SEARCH_HINTS[state.section]} /></label>{state.section === 'users' && <label>搜索范围<select aria-label="搜索范围" value={draft.searchBy || 'identity'} onChange={(e) => update('searchBy', e.target.value)}><option value="identity">账号身份</option><option value="contact">反馈联系方式（未验证）</option></select></label>}{state.section !== 'users' && <label>用户 ID<input maxLength={200} value={draft.userId || ''} onChange={(e) => update('userId', e.target.value)} placeholder="精确匹配用户" /></label>}</div>
    <div className="ops-filter-row">{state.section === 'users' && <><SelectFilter title="邮箱验证" field="verified" values={['verified', 'unverified']} draft={draft} update={update} /><SelectFilter title="账号状态" field="status" values={['active', 'pending', 'review_required', 'completed']} draft={draft} update={update} /></>}{state.section === 'jobs' && <><SelectFilter title="执行状态" field="status" values={JOB_STATES} draft={draft} update={update} /><SelectFilter title="任务类型" field="type" values={['generate', 'refine']} draft={draft} update={update} /><SelectFilter title="运营跟进" field="followup" values={['unreviewed', 'followup', 'resolved']} draft={draft} update={update} /><label>模型<input maxLength={120} value={draft.model || ''} onChange={(e) => update('model', e.target.value)} placeholder="模型名称" /></label></>}{state.section === 'community' && <><SelectFilter title="审核状态" field="status" values={REVIEW_STATES} draft={draft} update={update} /><label>能力分类<input maxLength={120} value={draft.category || ''} onChange={(e) => update('category', e.target.value)} placeholder="按已有分类检索" /></label></>}
      <label>{state.section === 'users' ? '注册日期从' : '创建日期从'}<input type="date" value={draft.fromDate || ''} max={draft.toDate || undefined} onChange={(e) => update('fromDate', e.target.value)} /></label><label>至（含当天）<input type="date" value={draft.toDate || ''} min={draft.fromDate || undefined} onChange={(e) => update('toDate', e.target.value)} /></label><label>排序<select aria-label="排序" value={draft.sort || 'newest'} onChange={(e) => update('sort', e.target.value)}><option value="newest">最新创建优先</option><option value="oldest">最早创建优先</option>{state.section === 'jobs' && <option value="duration_desc">完成耗时最长优先</option>}</select></label>
    </div><div className="ops-filter-footer"><small>日期按当前浏览器时区查询；留空表示全部时间。</small><div><button type="button" onClick={() => change({ section: state.section, pageSize: state.pageSize || 20 }, true)}>清除筛选</button><button className="ops-primary" type="submit">应用筛选</button></div></div>
  </form>;
}
function Overview({ apiBase, state, go, change, refresh, retry }) {
  const selected = state.fromDate || state.toDate ? state : { ...state, ...rangeDates(7) };
  const result = useAdminData(apiBase, 'adminOverview', queryFor(selected), refresh);
  const d = result.data;
  const card = (title, value, detail, target, filter, icon) => <button className="ops-metric" onClick={() => go(target, filter)}><div><span>{title}</span>{icon || <ArrowUpRight size={18} />}</div><strong>{value}</strong><p>{detail}</p></button>;
  const scoped = { fromDate: selected.fromDate, toDate: selected.toDate };
  return <><div className="ops-overview-range"><div><h2>运营总览</h2><p>看清最近的注册与任务，及时处理待审核内容。</p></div><form onSubmit={(e) => { e.preventDefault(); const data = new FormData(e.currentTarget); change({ ...Object.fromEntries(data), page: '' }); }} key={`${selected.fromDate}-${selected.toDate}`}><label>统计范围<select aria-label="统计范围" value={state.range || '7'} onChange={(e) => change({ ...rangeDates(Number(e.target.value) || 7), range: e.target.value })}><option value="7">近 7 天</option><option value="30">近 30 天</option><option value="90">近 90 天</option><option value="custom">自定义</option></select></label><label>开始日期<input type="date" name="fromDate" required defaultValue={selected.fromDate} /></label><label>结束日期<input type="date" name="toDate" required defaultValue={selected.toDate} /></label><input type="hidden" name="range" value="custom" /><button type="submit">查询</button></form></div><State {...result} retry={retry}>{d && <><div className="ops-metrics">
    {card('用户总数', d.users.available ? d.users.total : '暂不可用', '当前仍存在的账号 · 全部时间', 'users', {}, <Users size={18} />)}
    {card('新增注册', d.users.available ? d.users.registered : '暂不可用', '统计范围内创建且仍存在的账号', 'users', scoped)}
    {card('近期任务', d.tasks.available ? d.tasks.total : '暂不可用', '统计范围内创建的任务 · 包含访客任务', 'jobs', scoped, <Activity size={18} />)}
    {card('待审核社区题', d.community.available ? d.community.pending : '暂不可用', '当前待处理、已归组与待审核候选 · 全部时间', 'community', { status: 'open' })}
  </div><div className="ops-overview-panels"><section className="ops-card"><div className="ops-card-head"><h3>任务执行情况</h3><button className="ops-link" onClick={() => go('jobs', scoped)}>查看任务 →</button></div>{d.tasks.available ? <><div className="ops-task-counts">{JOB_STATES.map((status) => <button key={status} onClick={() => go('jobs', { ...scoped, status })}><Badge value={status} /><strong>{d.tasks.counts[status] || 0}</strong></button>)}</div><p>已结束任务成功率：<strong>{d.tasks.successRate == null ? '暂无已结束任务' : `${(d.tasks.successRate * 100).toFixed(1)}%`}</strong></p></> : <p role="alert">{d.tasks.error}</p>}<p className="ops-muted">成功率 = 成功 ÷（成功 + 失败）。仅统计所选日期内创建的任务；排队与执行中的任务不进入分母，耗时以开始到完成计算。</p></section><section className="ops-card ops-review-guide"><ShieldCheck size={23} /><h3>从提交到候选，处理过程可追溯</h3><p>审核只影响社区候选池。已通过的题目仍需独立纳入正式题集并发布，已有评估结果保持原有版本。</p><button onClick={() => go('community', { status: 'open' })}>进入待审核列表 <ArrowUpRight size={16} /></button></section></div>{[d.users, d.community].filter((s) => !s.available).map((s, i) => <p key={i} role="alert" className="ops-error">{s.error}</p>)}<p className="ops-muted ops-stats-note">统计读取时间：{date(d.asOf)}。日期按本地自然日（结束日包含全天）查询，各数据源分别读取，属于当前快照；已注销并清理的账号和业务数据不计入历史累计。</p></>}</State></>;
}
function Records({ apiBase, state, change, go, open, refresh, retry }) {
  const result = useAdminData(apiBase, ACTIONS[state.section], queryFor(state), refresh), rows = result.data?.rows || [];
  useEffect(() => { if (!result.loading && result.data) requestAnimationFrame(() => window.scrollTo(0, Number(window.history.state?.opsScroll || 0))); }, [result.loading, result.data]);
  const detail = (r) => open(r.id || r.submissionId);
  return <><div className="ops-list-heading"><h2>{SECTIONS.find(([id]) => id === state.section)?.[1]}</h2><p>{state.section === 'community' ? '审核状态与正式发布分开记录；通过后进入下期候选。' : state.section === 'users' ? '以用户 ID 归并账号、登录方式与关联业务记录。已完成注销的账号通常已从认证库移除。' : state.section === 'jobs' ? '执行状态和运营跟进独立显示，点击任务查看输入、结果与处理记录。' : '展示真实用户反馈；联系方式为用户自填信息。'}</p></div><Filters state={state} change={change} /><State {...result} retry={retry}>{result.data && <><p className="ops-table-hint">左右滑动查看全部列；点击标题进入详情。</p><div className="ops-table-wrap"><table><caption className="ops-sr-only">{SECTIONS.find(([id]) => id === state.section)?.[1]}列表</caption><thead><tr>{HEADERS[state.section].map((h) => <th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{rows.map((r) => <tr key={r.id || r.submissionId}>
    {state.section === 'users' ? <><td><button className="ops-link" onClick={() => detail(r)}>{r.name || r.email || r.id}</button><small>{r.email}</small><code>{r.id}</code></td><td>{r.loginMethods.map(label).join('、') || '未记录'}</td><td><Badge value={r.emailVerified ? 'verified' : 'unverified'} /><Badge value={r.status}>{stateAccountLabel('status', r.status, 'users')}</Badge></td><td>{date(r.createdAt)}</td><td>{date(r.latestRetainedLoginAt)}</td><td>{r.activeSessions}</td></> : state.section === 'jobs' ? <><td><button className="ops-link ops-clamp" onClick={() => detail(r)}>{r.title}</button><code title={r.id}>{r.id}</code></td><td><Identity id={r.userId} email={r.email} go={go} /></td><td><Badge value={r.status} /><Badge value={r.followup} /><small>{r.resultCount} 张结果</small></td><td>{label(r.type)}<small>主：{r.models.main || '未记录'}</small><small>图：{r.models.image || '未记录'}</small></td><td>{date(r.createdAt)}</td><td>{duration(r.durationMs)}</td></> : state.section === 'community' ? <><td><button className="ops-link ops-clamp" onClick={() => detail(r)}>{r.prompt}</button><code title={r.submissionId}>{r.submissionId}</code></td><td><Identity id={r.userId} go={go} /></td><td>{r.capability || '未分类'}</td><td><Badge value={r.status} /></td><td>{date(r.createdAt)}</td></> : <><td><details><summary className="ops-clamp">{r.message}</summary><p className="ops-pre">{r.message}</p></details><small>{r.category || '未分类'} · {r.platform || '未记录来源'}</small></td><td><Identity id={r.userId} email={r.email} go={go} /></td><td>{r.contact || '未提供'}{r.userId && <small>完整信息见用户详情</small>}</td><td>{r.jobId ? <button className="ops-link" onClick={() => go('jobs', { id: r.jobId })}>{r.jobId}</button> : '未关联'}</td><td><Badge value={r.status} /><small>{date(r.createdAt)}</small></td></>}
  </tr>)}</tbody></table>{!rows.length && <div className="ops-empty"><Search size={26} /><h3>{result.data.pagination.total ? '这一页没有记录' : '没有符合条件的记录'}</h3><p>可调整关键词、日期或状态后再查询。</p><button onClick={() => change(result.data.pagination.total ? { page: 1 } : { section: state.section }, !result.data.pagination.total)}>{result.data.pagination.total ? '返回第一页' : '清除筛选'}</button></div>}</div><Pager pagination={result.data.pagination} change={change} /></>}</State></>;
}
export default function AdminWorkspace({ apiBase, health, defaultSection = 'overview' }) {
  const [state, setState] = useState(() => readAdminLocation(defaultSection)), [refresh, setRefresh] = useState(0);
  const savedSections = useRef({});
  useEffect(() => { const pop = () => setState(readAdminLocation(defaultSection)); window.addEventListener('popstate', pop); return () => window.removeEventListener('popstate', pop); }, [defaultSection]);
  const navigate = (next, { replace = false, parent = false } = {}) => {
    window.history.replaceState({ ...window.history.state, opsScroll: window.scrollY }, '', window.location.href);
    savedSections.current[state.section] = { ...state, id: '' };
    const url = adminUrl(next);
    window.history[replace ? 'replaceState' : 'pushState']({ opsScroll: 0, ...(parent ? { opsParent: true } : {}) }, '', url);
    setState(next); window.scrollTo(0, 0);
  };
  const change = (patch, reset = false) => navigate(reset ? patch : { ...state, ...patch });
  const go = (section, query = {}) => navigate({ section, ...query });
  const open = (id) => navigate({ ...state, id }, { parent: true });
  const back = () => { if (window.history.state?.opsParent) window.history.back(); else navigate({ ...state, id: '' }, { replace: true }); };
  const retry = () => setRefresh((n) => n + 1);
  return <section className="ops-workspace" aria-label="站长运营后台"><header className="ops-header"><div><span className="ops-eyebrow"><ShieldCheck size={15} />TUYAN ADMIN</span><h1>站长运营后台</h1><p>账号、任务与社区内容，在同一个工作区处理。</p></div><button onClick={retry}><RefreshCcw size={16} />刷新数据</button></header><div className="ops-layout"><nav className="ops-nav" aria-label="后台导航">{SECTIONS.map(([id, title]) => <button key={id} aria-current={state.section === id ? 'page' : undefined} onClick={() => navigate(savedSections.current[id] || { section: id })}>{id === 'overview' ? <LayoutDashboard size={17} /> : id === 'users' ? <Users size={17} /> : id === 'jobs' ? <Activity size={17} /> : <span className="ops-nav-dot" />}{title}</button>)}<p>站长专用<br />所有操作由服务端校验权限</p></nav><div className="ops-content" key={`${state.section}-${state.id || ''}`}>
    {state.id && state.section === 'users' ? <UserDetail apiBase={apiBase} id={state.id} back={back} go={go} key={refresh} /> : state.id && state.section === 'jobs' ? <TaskDetail apiBase={apiBase} id={state.id} back={back} go={go} key={refresh} /> : state.id && state.section === 'community' ? <CommunityDetail apiBase={apiBase} id={state.id} back={back} go={go} key={refresh} /> : state.section === 'overview' ? <Overview apiBase={apiBase} state={state} go={go} change={change} refresh={refresh} retry={retry} /> : state.section === 'benchmark' ? <><h2>评测运行（高级）</h2><p className="ops-notice">这里管理模型候选、预算、运行、审核和正式发布。相关操作可能触发真实评测与费用，请按既有预算和发布流程操作。</p><BenchmarkAdminPanel apiBase={apiBase} health={health} /></> : <Records apiBase={apiBase} state={state} change={change} go={go} open={open} refresh={refresh} retry={retry} />}
  </div></div></section>;
}
