import assert from 'node:assert/strict';
import { startIdentityFixture, createFixtureClient } from './identity-fixture.mjs';

const fixture = await startIdentityFixture(process.env.ACCOUNT_LIFECYCLE_TEST_MONGO_URI || '');
const checks = [];
const pass = (name) => { checks.push(name); console.log(`PASS ${name}`); };
const json = async (response, status = 200) => { const body = await response.json(); assert.equal(response.status, status, JSON.stringify(body)); return body; };
const user = async (client) => (await json(await client.request('get-session')))?.user;
async function oauthStart(client, provider, intent = 'login', purpose) {
  const data = await json(await client.request('identity/oauth/start', { provider, intent, ...(purpose ? { purpose } : {}) }));
  const url = new URL(data.url); url.pathname = '/approve';
  const approval = await client.request(url.toString()); assert.equal(approval.status, 302);
  return approval.headers.get('location');
}
async function oauth(client, provider, intent = 'login', purpose) {
  const callback = await oauthStart(client, provider, intent, purpose);
  const response = await client.request(callback); assert.equal(response.status, 302);
  return new URL(response.headers.get('location')).searchParams.get('auth_result');
}
const manage = (client) => oauth(client, 'github', 'reauth', 'manage');
try {
  const first = createFixtureClient(fixture);
  assert.equal((await json(await first.request('identity/capabilities'))).providers.google, true);
  assert.equal((await first.request('identity/methods')).status, 401); pass('anonymous identity management rejected');
  assert.equal(await oauth(first, 'github'), 'signed-in');
  const github = await user(first); assert.ok(github.id); assert.equal(github.email, ''); assert.equal(github.emailVerified, false);
  assert.equal(await fixture.db.collection('user').countDocuments({}), 1);
  const account = await fixture.db.collection('account').findOne({ providerId: 'github' });
  for (const field of ['accessToken', 'refreshToken', 'idToken', 'password']) assert.equal(account[field], undefined);
  pass('GitHub first authorization creates one internal ID without email verification or persisted tokens');
  const again = createFixtureClient(fixture); assert.equal(await oauth(again, 'github'), 'signed-in'); assert.equal((await user(again)).id, github.id);
  pass('GitHub repeated authorization retains internal identity');
  assert.equal(await manage(first), 'verified-manage');
  assert.equal((await json(await first.request('identity/unlink', { provider: 'github' }), 409)).code, 'IDENTITY_LAST_METHOD');
  pass('cannot unlink the only usable method');
  assert.equal(await oauth(first, 'google', 'bind'), 'linked');
  assert.equal((await json(await first.request('identity/methods'))).methods.length, 2); assert.equal((await user(first)).id, github.id);
  const google = createFixtureClient(fixture); assert.equal(await oauth(google, 'google'), 'signed-in'); assert.equal((await user(google)).id, github.id);
  pass('explicit Google binding and subsequent login share the existing ID');
  fixture.profiles.google.subject = 'google-wrong';
  assert.equal(await oauth(first, 'google', 'reauth', 'delete'), 'IDENTITY_WRONG_ACCOUNT');
  fixture.profiles.google.subject = 'google-100001';
  pass('reauthorizing a different provider account cannot authorize deletion');
  await fixture.db.collection('paperbanana_jobs').insertOne({ _id: 'retained-task', userId: github.id, status: 'succeeded', resultImages: [] });
  assert.equal(await manage(first), 'verified-manage');
  const challenge = await json(await first.request('identity/email/request', { email: 'bound@example.test' }));
  assert.equal(challenge.expiresIn, 300);
  const stored = await fixture.db.collection('authIdentityChallenges').findOne({ kind: 'email-bind' }); assert.notEqual(stored.codeHash, fixture.mails.at(-1).code); assert.equal(stored.code, undefined);
  assert.equal((await json(await first.request('identity/email/verify', { challenge: challenge.challenge, code: '000000', password: 'bound-password-123' }), 400)).code, 'IDENTITY_CODE_INVALID');
  assert.equal((await json(await first.request('identity/email/verify', { challenge: challenge.challenge, code: fixture.mails.at(-1).code, password: 'bound-password-123' }))).ok, true);
  assert.equal((await user(first)).id, github.id); assert.equal((await user(first)).emailVerified, true);
  const byEmail = createFixtureClient(fixture); await json(await byEmail.request('sign-in/email', { email: 'bound@example.test', password: 'bound-password-123' })); assert.equal((await user(byEmail)).id, github.id);
  assert.ok(await fixture.db.collection('paperbanana_jobs').findOne({ _id: 'retained-task', userId: github.id }));
  assert.equal((await json(await first.request('identity/email/verify', { challenge: challenge.challenge, code: fixture.mails.at(-1).code, password: 'bound-password-123' }), 400)).code, 'IDENTITY_CODE_EXPIRED');
  pass('explicit email verification binds a password without changing user ID; code errors and replay rejected');
  await json(await first.request('identity/reauth/password', { password: 'bound-password-123', purpose: 'manage' }));
  const unlinks = await Promise.all(['google', 'github'].map((provider) => first.request('identity/unlink', { provider })));
  assert.deepEqual(unlinks.map((r) => r.status).sort(), [200, 401]);
  pass('concurrent mutations consume proof once and keep a usable login method');
  const existing = createFixtureClient(fixture);
  await json(await existing.request('sign-up/email', { email: 'existing@example.test', password: 'existing-password-123', name: '已有用户' }));
  const existingRow = await fixture.db.collection('user').findOne({ email: 'existing@example.test' });
  fixture.profiles.google = { subject: 'google-existing', name: '同邮箱授权', email: 'existing@example.test', emailVerified: true };
  const conflict = createFixtureClient(fixture); assert.equal(await oauth(conflict, 'google'), 'IDENTITY_EMAIL_CONFLICT'); assert.equal(await user(conflict), undefined);
  assert.equal((await fixture.db.collection('user').findOne({ _id: existingRow._id })).emailVerified, false);
  assert.equal(await fixture.db.collection('account').countDocuments({ providerId: 'google', accountId: 'google-existing' }), 0);
  pass('matching email never merges or verifies an existing email account');
  assert.equal((await existing.request('sign-in/email', { email: 'existing@example.test', password: 'existing-password-123' })).status, 403);
  const verificationToken = await fixture.verifier.issue({ id: String(existingRow._id) });
  const preview = await existing.request(`verify-email?token=${verificationToken}`); assert.equal(preview.status, 302);
  assert.equal((await fixture.db.collection('user').findOne({ _id: existingRow._id })).emailVerified, false);
  await json(await existing.request('verify-email', { token: verificationToken }));
  await json(await existing.request('sign-in/email', { email: 'existing@example.test', password: 'existing-password-123' }));
  await json(await existing.request('identity/reauth/password', { password: 'existing-password-123', purpose: 'manage' }));
  assert.equal(await oauth(existing, 'google', 'bind'), 'linked'); assert.equal((await user(existing)).id, String(existingRow._id));
  pass('original email identity verification followed by explicit linking resolves conflict safely');
  const rejected = createFixtureClient(fixture), callback = await oauthStart(rejected, 'github');
  const noCookie = createFixtureClient(fixture); assert.equal(new URL((await noCookie.request(callback)).headers.get('location')).searchParams.get('auth_result'), 'OAUTH_STATE_INVALID');
  const firstCallback = await rejected.request(callback); assert.equal(firstCallback.status, 302);
  assert.equal(new URL((await rejected.request(callback)).headers.get('location')).searchParams.get('auth_result'), 'OAUTH_STATE_INVALID');
  pass('OAuth callback browser binding and state replay protection');
  const cancelled = createFixtureClient(fixture); const cancelUrl = new URL(await oauthStart(cancelled, 'google')); cancelUrl.searchParams.delete('code'); cancelUrl.searchParams.set('error', 'access_denied');
  assert.equal(new URL((await cancelled.request(cancelUrl.toString())).headers.get('location')).searchParams.get('auth_result'), 'OAUTH_CANCELLED');
  for (const failure of ['nonce', 'issuer', 'token']) {
    fixture.failures[failure] = true; assert.equal(await oauth(createFixtureClient(fixture), 'google'), 'OAUTH_AUTHORIZATION_FAILED'); fixture.failures[failure] = false;
  }
  pass('authorization cancellation, bad Google nonce/issuer and token service failure fail closed');
  // A separate OAuth-only identity exercises email delivery failures and expiry.
  fixture.profiles.github = { subject: '900009', name: '无密码用户', email: '', emailVerified: false };
  const passwordless = createFixtureClient(fixture); assert.equal(await oauth(passwordless, 'github'), 'signed-in'); const oldId = (await user(passwordless)).id;
  await manage(passwordless); fixture.failures.email = true;
  assert.equal((await json(await passwordless.request('identity/email/request', { email: 'outage@example.test' }), 503)).code, 'IDENTITY_EMAIL_UNAVAILABLE'); fixture.failures.email = false;
  assert.equal(await fixture.db.collection('authIdentityChallenges').countDocuments({ kind: 'email-bind', userId: oldId }), 0);
  await manage(passwordless); const expired = await json(await passwordless.request('identity/email/request', { email: 'expired@example.test' }));
  await fixture.db.collection('authIdentityChallenges').updateMany({ kind: 'email-bind', userId: oldId }, { $set: { expiresAt: new Date(0) } });
  assert.equal((await json(await passwordless.request('identity/email/verify', { challenge: expired.challenge, code: fixture.mails.at(-1).code, password: 'new-password-123' }), 400)).code, 'IDENTITY_CODE_EXPIRED');
  pass('email transport failure removes challenge; explicit expiry rejected');
  const staleClient = createFixtureClient(fixture), staleCallback = await oauthStart(staleClient, 'github');
  assert.equal(await oauth(passwordless, 'github', 'reauth', 'delete'), 'verified-delete');
  const deleted = await json(await passwordless.request(fixture.apiBase + '/api/account/delete', { verification: 'identity' })); assert.equal(deleted.ok, true);
  assert.equal(await fixture.db.collection('user').countDocuments({ _id: account.userId }), 1, 'unrelated original account preserved');
  assert.equal(new URL((await staleClient.request(staleCallback)).headers.get('location')).searchParams.get('auth_result'), 'ACCOUNT_LIFECYCLE_CLOSED');
  const fresh = createFixtureClient(fixture); assert.equal(await oauth(fresh, 'github'), 'signed-in'); assert.notEqual((await user(fresh)).id, oldId);
  assert.equal(await user(passwordless), undefined);
  pass('OAuth-only deletion uses scoped reauthentication; old callbacks/sessions rejected and fresh registration gets a new ID');
  const badOrigin = await fresh.request('identity/reauth/password', { password: 'x', purpose: 'manage' }, { headers: { origin: 'https://attacker.invalid', 'content-type': 'application/json' } }); assert.equal(badOrigin.status, 403);
  for (const path of ['unlink-account', 'link-social', 'change-email', 'set-password', 'delete-user']) assert.equal((await fresh.request(path, {})).status, 404);
  pass('cross-origin writes and alternate library mutation routes blocked');
  // Reset counters between independent scenarios in the disposable database.
  await fixture.db.collection('authIdentityRateLimits').deleteMany({});
  await fixture.db.collection('rateLimit').deleteMany({});
  const resetPeer = createFixtureClient(fixture);
  await json(await resetPeer.request('sign-in/email', { email: 'existing@example.test', password: 'existing-password-123' }));
  await json(await existing.request('identity/reauth/password', { password: 'existing-password-123', purpose: 'manage' }));
  await json(await existing.request('request-password-reset', { email: 'existing@example.test', redirectTo: fixture.webBase + '/account/reset-password.html' }));
  const resetRow = await fixture.db.collection('verification').findOne({ identifier: /^reset-password:/, value: String(existingRow._id) });
  assert.ok(resetRow);
  const resetToken = resetRow.identifier.slice('reset-password:'.length);
  await json(await existing.request('reset-password/?token=' + resetToken, { newPassword: 'reset-password-123' }));
  assert.equal(await user(existing), undefined); assert.equal(await user(resetPeer), undefined);
  assert.equal(await fixture.db.collection('authIdentityChallenges').countDocuments({ userId: String(existingRow._id) }), 0);
  assert.equal((await existing.request('reset-password', { token: resetToken, newPassword: 'replay-password-123' })).status, 400);
  assert.equal((await existing.request('sign-in/email', { email: 'existing@example.test', password: 'existing-password-123' })).status, 401);
  await json(await existing.request('sign-in/email', { email: 'existing@example.test', password: 'reset-password-123' }));
  await json(await resetPeer.request('sign-in/email', { email: 'existing@example.test', password: 'reset-password-123' }));
  await json(await existing.request('change-password', { currentPassword: 'reset-password-123', newPassword: 'changed-password-123', revokeOtherSessions: true }));
  assert.equal(await user(resetPeer), undefined); assert.equal((await user(existing)).id, String(existingRow._id));
  pass('existing reset/change-password endpoints work, reset is single-use and old sessions/grants are revoked');
  await json(await existing.request('request-password-reset', { email: 'existing@example.test', redirectTo: fixture.webBase + '/account/reset-password.html' }));
  const staleReset = await fixture.db.collection('verification').findOne({ identifier: /^reset-password:/, value: String(existingRow._id) });
  await json(await existing.request('identity/reauth/password', { password: 'changed-password-123', purpose: 'manage' }));
  await json(await existing.request('identity/unlink', { provider: 'email' }));
  assert.equal((await existing.request('reset-password', { token: staleReset.identifier.slice('reset-password:'.length), newPassword: 'stale-password-123' })).status, 400);
  assert.equal((await json(await existing.request('identity/methods'))).methods.some((m) => m.provider === 'email'), false);
  pass('unlinking email invalidates previously issued reset tokens and cannot recreate removed credentials');
  const duplicateEmail = createFixtureClient(fixture);
  const neutral = await json(await duplicateEmail.request('sign-up/email', { email: 'existing@example.test', password: 'different-password-123', name: '重复邮箱' }));
  assert.equal(neutral.emailVerificationRequired, true); assert.equal(await fixture.db.collection('user').countDocuments({ email: 'existing@example.test' }), 0);
  assert.equal(await user(duplicateEmail), undefined);
  await manage(fresh);
  assert.equal((await json(await fresh.request('identity/email/request', { email: 'existing@example.test' }), 409)).code, 'IDENTITY_EMAIL_CONFLICT');
  pass('social-first email registration stays neutral and binding to another social account email is rejected');
  fixture.profiles.google = { subject: 'concurrent-google', name: '并发解绑', email: '', emailVerified: false };
  assert.equal(await oauth(fresh, 'google', 'bind'), 'linked');
  const concurrentPeer = createFixtureClient(fixture); assert.equal(await oauth(concurrentPeer, 'github'), 'signed-in');
  await manage(fresh); await manage(concurrentPeer);
  const concurrent = await Promise.all([fresh.request('identity/unlink', { provider: 'github' }), concurrentPeer.request('identity/unlink', { provider: 'google' })]);
  assert.equal(concurrent.filter((response) => response.ok).length, 1);
  const currentId = String((await fixture.db.collection('account').findOne({ accountId: { $in: ['900009', 'concurrent-google'] } })).userId);
  assert.equal(await fixture.db.collection('account').countDocuments({ userId: (await fixture.db.collection('account').findOne({ accountId: { $in: ['900009', 'concurrent-google'] } })).userId }), 1);
  assert.ok(currentId); pass('different sessions cannot concurrently unlink the final two authentication methods');
  const rateClient = createFixtureClient(fixture);
  await fixture.db.collection('authIdentityRateLimits').deleteMany({});
  for (let i = 0; i < 30; i++) await json(await rateClient.request('identity/oauth/start', { provider: 'google', intent: 'login' }));
  const limited = await rateClient.request('identity/oauth/start', { provider: 'google', intent: 'login' });
  assert.equal((await json(limited, 429)).code, 'IDENTITY_RATE_LIMITED'); assert.ok(Number(limited.headers.get('retry-after')) > 0);
  pass('OAuth start uses a persistent IP limit with retry-after');
  assert.equal(checks.length, 20); console.log(JSON.stringify({ passed: checks.length, realProviderCalls: 0, productionWrites: 0 }));
} finally { await fixture.cleanup(); }
