// Generated by scripts/sync-model-catalog.mjs. Do not edit by hand.
import { unpackModelCatalog } from './unpack-model-catalog'
const catalog = unpackModelCatalog(require('./static-model-catalog-data.js'))
export const EXTENDED_MODEL_CHANNELS: Record<string, any> = catalog.channels
export const STATIC_MODEL_REGISTRY_VERSION = "2026-09-22.v22"
export const STATIC_MODEL_REGISTRY: Record<string, any> = catalog.registry
