const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const source = fs.readFileSync(path.resolve(__dirname, '../paperbanana-api.ts'), 'utf8')

assert.match(source, /titleZh:\s*string/)
assert.match(source, /introZh:\s*string/)
assert.match(source, /shortIntroZh:\s*string/)
assert.match(source, /detailZh:\s*string/)
assert.match(source, /visualCategory:\s*string/)
assert.match(source, /researchDomain:\s*string/)
assert.match(source, /keywords:\s*string\[\]/)
assert.match(source, /corpusVersion:\s*string/)
assert.match(source, /titleZh:\s*limitText\(item\.titleZh \|\| item\.title_zh/)
assert.match(source, /shortIntroZh = limitText\(item\.shortIntroZh \|\| item\.short_intro_zh \|\| item\.introZh \|\| item\.intro_zh/)
assert.match(source, /id:\s*String\(item\.id \|\| item\._id \|\| ''\)/)
assert.match(source, /referenceSearchText\(item: RetrievedReference\)/)
assert.match(source, /referenceLibraryPositiveInteger\(body\.pageSize \?\? body\.limit, 12, 306\)/)
assert.match(source, /Number\.isInteger\(number\) \|\| number <= 0/)
assert.match(source, /clamp\(Number\(options\.limit \|\| 24\), 1, 306\)/)
assert.match(source, /resolveManualRetrievedReferences/)
assert.match(source, /id: \{ \$in: ids \}/)

console.log('reference localization backend policy ok')
