import {useState,useRef} from 'react'
import {readConnectionLibrary,saveConnectionLibrary,connectionFacts,profilePatch,exportUniversalConfiguration,importUniversalConfiguration,UNIVERSAL_FILE_MAX_BYTES} from '../lib/universalProfiles.js'

/** Profiles are snapshots. Applying one edits exactly this role, never another role or a key. */
export default function UniversalConnections({role,label,draft,thinking,onChange,onImportThinking}) {
  const [profiles,setProfiles]=useState(readConnectionLibrary),[selected,setSelected]=useState(draft.ui?.connectionProfileId||''),[name,setName]=useState(draft.ui?.connectionName||''),[status,setStatus]=useState(''),[preview,setPreview]=useState(null)
  const file=useRef(null)
  const chosen=profiles.find(p=>p.id===selected)
  const persist=next=>{try{setProfiles(saveConnectionLibrary(next));return true}catch(e){setStatus(e.message);return false}}
  const save=update=>{try{const p={id:update?chosen.id:crypto.randomUUID(),name:name.trim(),connection:connectionFacts(draft.custom)};if(!p.name)throw Error('请先填写连接名称。');if(persist(update?profiles.map(x=>x.id===p.id?p:x):[...profiles,p])){setSelected(p.id);onChange({ui:{connectionProfileId:p.id,connectionName:p.name}});setStatus('连接已保存到浏览器，不含密钥。其他角色的当前配置保持原样。')}}catch(e){setStatus(e.message)}}
  const download=()=>{try{const value=exportUniversalConfiguration(role,draft,profiles,thinking);const url=URL.createObjectURL(new Blob([value],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`tuyan-universal-${role}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setStatus('已导出当前角色配置、思考偏好与连接列表，不含密钥或验证状态。')}catch(e){setStatus(e.message)}}
  const read=async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;setPreview(null);try{if(f.size>UNIVERSAL_FILE_MAX_BYTES)throw Error('配置文件超过 128 KiB。');setPreview(importUniversalConfiguration(await f.text(),role));setStatus('文件已读取，尚未修改配置，也未访问上游。')}catch(error){setStatus(error.message)}}
  return <details className="universal-details universal-connections"><summary>已命名连接与无密钥配置文件</summary>
    <p className="universal-hint">连接仅保存地址、协议、鉴权方式、目录规则与兼容变体。角色保存独立副本；更新或删除连接不会改写其他角色。</p>
    <label className="field"><span>已保存连接</span><select aria-label={`${label} 已保存连接`} value={selected} onChange={e=>{setSelected(e.target.value);setName(profiles.find(p=>p.id===e.target.value)?.name||'');onChange({ui:{connectionProfileId:e.target.value,connectionName:profiles.find(p=>p.id===e.target.value)?.name||''}})}}><option value="">选择连接</option>{profiles.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label>
    {chosen&&<><p className="universal-hint">{chosen.connection.protocol} · {chosen.connection.baseUrl}</p><div className="universal-recovery"><button type="button" className="universal-button" onClick={()=>{onChange(profilePatch(chosen));setStatus(`已将连接应用到${label}的当前页草稿；型号、能力和其他角色保留。绑定变化会清除本角色旧 Key。`)}}>应用连接到{label}（不含密钥）</button><button type="button" className="universal-button" onClick={()=>{if(persist(profiles.filter(p=>p.id!==chosen.id))){setSelected('');setName('');onChange({ui:{connectionProfileId:'',connectionName:''}});setStatus('已删除连接条目，已应用到各角色的副本保留。')}}}>删除连接条目</button></div></>}
    <label className="field"><span>连接名称</span><input aria-label={`${label} 连接名称`} maxLength={80} value={name} onChange={e=>{setName(e.target.value);onChange({ui:{connectionName:e.target.value}})}}/></label>
    <div className="universal-recovery"><button type="button" className="universal-button" onClick={()=>save(false)}>将当前连接另存到浏览器</button>{chosen&&<button type="button" className="universal-button" onClick={()=>save(true)}>以当前连接更新「{chosen.name}」</button>}</div>
    <p className="universal-hint">导出范围：当前角色的型号、能力、限额、尺寸及适用思考偏好，加上已命名连接。不包含任何 Key、认证头、会话、任务恢复凭据或验证状态。</p>
    <div className="universal-recovery"><button type="button" className="universal-button" onClick={download}>导出无密钥配置</button><button type="button" className="universal-button" onClick={()=>file.current.click()}>选择配置文件并预览</button><input ref={file} type="file" accept=".json,application/json" hidden aria-label={`${label} 导入文件`} onChange={read}/></div>
    {preview&&<section className="universal-import-preview" aria-label={`${label} 导入预览`}><p>{preview.message}</p><p>{preview.draft.custom.baseUrl} · {preview.draft.custom.protocol} · {preview.draft.modelId||'未填写型号'}</p><p>文件中的 {preview.profiles.length} 个连接仅在下方明确保存后进入浏览器；同名或同标识条目不会被覆盖。</p><div className="universal-recovery"><button type="button" className="universal-button" onClick={()=>{onChange(preview.draft);if(preview.thinking)onImportThinking?.(role,preview.thinking);setStatus('已导入当前角色草稿，请核对并重新确认能力；未执行请求。');setPreview(null)}}>导入到{label}草稿</button>{preview.profiles.length>0&&<button type="button" className="universal-button" onClick={()=>{const additions=preview.profiles.map(p=>({...p,id:crypto.randomUUID(),name:profiles.some(x=>x.name===p.name)?`${p.name.slice(0,70)}（导入）`:p.name}));if(persist([...profiles,...additions])){setStatus('文件连接已作为新条目保存，现有条目与角色配置未改变。');setPreview({...preview,profiles:[]})}}}>将文件连接另存到浏览器</button>}<button type="button" className="universal-button" onClick={()=>{setPreview(null);setStatus('已取消导入，当前配置未改变。')}}>取消导入</button></div></section>}
    {status&&<p className="universal-status neutral" role="status">{status}</p>}
  </details>
}
