import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { test } from 'node:test'

const workflow = readFileSync(new URL('../../../.github/workflows/finalize-v1-external-object-retirement.yml', import.meta.url), 'utf8')

test('externally deleted V1 objects are reverified before exact DB retirement', () => {
  assert.match(workflow, /33515513815/u)
  assert.match(workflow, /v1-retirement-inspect-33515513815/u)
  assert.match(workflow, /\(\.inventory\.exclusiveObjects \| length\) == 253/u)
  assert.match(workflow, /\(\.inventory\.sharedObjects \| length\) == 0/u)
  assert.match(workflow, /exclusiveObjects\.length\s*!==\s*253/u)
  assert.match(workflow, /sharedObjects\.length\s*!==\s*0/u)
  assert.match(workflow, /-e "ACTIVE_V2_RELEASE_HASH=\$ACTIVE_V2_RELEASE_HASH"/u)
  assert.match(workflow, /-e "INVENTORY_HASH=\$INVENTORY_HASH"/u)
  assert.match(workflow, /await oss\.head\(item\.objectKey\)/u)
  assert.match(workflow, /missing\s*!==\s*report\.inventory\.exclusiveObjects\.length/u)
  assert.match(workflow, /retire-v1-benchmark\.mongo\.js/u)
  assert.match(workflow, /mongodb:\/tmp\/retire-v1-benchmark\.mongo\.js/u)
  assert.match(workflow, /mongodb sh -c/u)
  assert.doesNotMatch(workflow, /\bmongo:\/tmp|\bmongo sh -c/u)
  assert.match(workflow, /V1_EXTERNAL_STAGE:objects_absent_verified/u)
  assert.match(workflow, /V1_EXTERNAL_STAGE:db_script_completed/u)
  assert.match(workflow, /dbReceipts\.length!==1/u)
  assert.match(workflow, /db_result_normalized/u)
  assert.match(workflow, /PAPERBANANA_V1_RECEIPT_PATH/u)
  assert.match(workflow, /CONTAINER_RECEIPT_PATH/u)
  assert.match(workflow, /"mongodb:\$CONTAINER_RECEIPT_PATH"/u)
  assert.doesNotMatch(workflow, /exec -T --user root mongodb rm -f \/tmp\/paperbanana-v1-retirement-receipt\.json/u)
  assert.match(workflow, /V1_EXTERNAL_STAGE:db_receipt_copied/u)
  assert.match(workflow, /local_mongo_script="\$GITHUB_WORKSPACE\/deploy\/hk-single-host\/scripts\/retire-v1-benchmark\.mongo\.js"/u)
  assert.match(workflow, /MONGO_SCRIPT_SHA/u)
  assert.match(workflow, /sha256sum "\$MONGO_SCRIPT_PATH"/u)
  assert.doesNotMatch(workflow, /"\$deploy_dir\/scripts\/retire-v1-benchmark\.mongo\.js"/u)
  assert.match(workflow, /generatedOrJudgeCalls:\s*0/u)
  assert.doesNotMatch(workflow, /\.delete\(|images\/generations|callImageModel|generate\(/u)
})
