const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

function read(relativePath) {
  return fs.readFileSync(path.join(__dirname, '..', 'miniprogram', relativePath), 'utf8')
}

const indexWxml = read('pages/index/index.wxml')
const indexWxss = read('pages/index/index.wxss')
const templateWxss = read('components/featured-template-studio/featured-template-studio.wxss')
const settingsWxml = read('components/generation-settings-sheet/generation-settings-sheet.wxml')
const settingsWxss = read('components/generation-settings-sheet/generation-settings-sheet.wxss')
const modelWxml = read('components/model-picker/model-picker.wxml')
const recordsWxss = read('pages/records/records.wxss')
const libraryWxml = read('components/reference-library/reference-library.wxml')
const libraryWxss = read('components/reference-library/reference-library.wxss')
const authWxml = read('components/auth-panel/auth-panel.wxml')
const authWxss = read('components/auth-panel/auth-panel.wxss')
const authTs = read('components/auth-panel/auth-panel.ts')
const accountWxml = read('components/account-settings/account-settings.wxml')
const accountWxss = read('components/account-settings/account-settings.wxss')

assert.doesNotMatch(indexWxml, /香港生产 API/)
assert.doesNotMatch(indexWxml, /summary-icon/)
assert.match(indexWxml, /summary-action/)
assert.match(indexWxml, /summary-details/)
assert.match(indexWxss, /\.summary-value\{[^}]*white-space:normal/)
assert.match(templateWxss, /\.template-apply\s*\{[^}]*display:flex[^}]*align-items:center[^}]*justify-content:center/)

for (const label of ['模型', '输出参数', '生成流程', '接入凭据']) assert.ok(settingsWxml.includes(label))
assert.match(settingsWxml, /wx:if="{{advancedExpanded}}"/)
assert.match(settingsWxml, /manual-library" wx:if="{{draft\.retrievalSetting === 'manual'}}"/)
assert.match(settingsWxml, /<reference-library task-name="\{\{libraryTaskName\}\}"/)
assert.match(settingsWxml, /<ratio-picker /)
assert.match(settingsWxss, /\.sheet-save\{[^}]*display:flex[^}]*align-items:center[^}]*justify-content:center/)

assert.match(modelWxml, /model-toolbar/)
assert.match(modelWxml, /provider-card/)
assert.match(modelWxml, /vendor-list/)
assert.match(modelWxml, /① 接入渠道/)
assert.match(modelWxml, /② 模型厂商/)
assert.match(modelWxml, /③ 具体模型/)
assert.doesNotMatch(modelWxml, /vendor-picker|更换渠道|全部厂商/)
assert.match(modelWxml, /model-list/)
assert.match(modelWxml, /仅显示当前角色可用模型/)
assert.match(modelWxml, /复制 ID/)

assert.match(recordsWxss, /\.job-record-meta\s*\{[^}]*grid-template-columns:repeat\(2/)
assert.match(recordsWxss, /\.job-models text:last-child\s*\{[^}]*white-space:normal/)
assert.match(recordsWxss, /\.job-prompt-preview\s*\{[^}]*max-height:none/)

assert.match(libraryWxml, /全库 306/)
assert.match(libraryWxml, /\{\{totalItems\}\} 项匹配/)
assert.match(libraryWxss, /\.library-search-input\{[^}]*min-width:0/)
assert.match(libraryWxss, /\.library-search-input\{[^}]*box-sizing:border-box/)

assert.match(authWxml, /忘记密码/)
assert.match(authTs, /submitText: '注册并验证邮箱'/)
assert.match(authWxml, /aria-label=/)
assert.match(authWxss, /box-sizing:\s*border-box/)
assert.match(authWxss, /min-height:\s*88rpx/)
assert.match(authWxss, /\.auth-close\s*\{[^}]*min-height:88rpx/)
assert.match(authWxss, /\.auth-form \.text-button\s*\{[^}]*min-height:88rpx/)
assert.match(authWxss, /\.auth-back\s*\{[^}]*min-height:88rpx/)
assert.match(accountWxml, /修改密码/)
assert.match(accountWxml, /重发验证邮件/)
assert.match(accountWxss, /box-sizing:\s*border-box/)
assert.match(accountWxss, /min-height:\s*88rpx/)
assert.match(accountWxss, /\.account-close\s*\{[^}]*min-height:88rpx/)
assert.match(accountWxss, /\.danger-confirm\s*\{[^}]*min-height:88rpx/)

console.log('mobile-ui-layout.test.cjs passed')
