import assert from 'node:assert/strict'
import { createHash } from 'node:crypto'
import fs from 'node:fs'
import { createRequire } from 'node:module'
import path from 'node:path'
import test from 'node:test'
import { fileURLToPath } from 'node:url'
import vm from 'node:vm'
import { packModelCatalog } from './lib/pack-model-catalog.mjs'

const root = fileURLToPath(new URL('../', import.meta.url))
const require = createRequire(import.meta.url)
const { unpackModelCatalog } = require('../apps/miniprogram/miniprogram/utils/unpack-model-catalog.js')

function verify(value) {
  const packed = packModelCatalog(value)
  const restored = unpackModelCatalog(JSON.parse(JSON.stringify(packed)))
  assert.equal(JSON.stringify(restored), JSON.stringify(value), 'field values and insertion order must round-trip exactly')
  assert.equal(createHash('sha256').update(JSON.stringify(restored)).digest('hex'), packed.sourceDigest)
  const containers = new Set()
  function walk(value) {
    if (!value || typeof value !== 'object') return
    assert.ok(!containers.has(value), 'shared wire references must expand into independent mutable containers')
    containers.add(value)
    Object.values(value).forEach(walk)
  }
  walk(restored)
  assert.deepEqual(packModelCatalog(value), packed, 'packing must be deterministic')
  return { packed, restored }
}

test('packing preserves Unicode, primitive values, object order and independent arrays', () => {
  const shared = { roles:['main','vision'], limits:{images:1, maxTokens:2048}, nullable:null, enabled:false }
  const value = {
    modelB:{...shared,label:'科学图研模型🌏版本 B',url:'https://example.org/models/science/B'},
    modelA:{...shared,label:'科学图研模型🌏版本 A',url:'https://example.org/models/science/A'},
    empty:'', literalNumbers:[0,-1,1.25], numericKeys:{10:'ten',2:'two'},
  }
  const {restored} = verify(value)
  restored.modelA.roles.push('fixture-change')
  restored.modelA.limits.images = 999
  assert.deepEqual(restored.modelB.roles, ['main','vision'])
  assert.equal(restored.modelB.limits.images, 1)
  for (const primitive of [null,true,false,0,-12,1.25,'']) verify(primitive)
})

test('the full catalog round-trips through the shipped decoder and stays below the unchanged package budget', () => {
  const source = fs.readFileSync(path.join(root,'apps/web/src/lib/staticModelCatalog.js'),'utf8').replace(/export const /g,'const ')
  const value = vm.runInNewContext(source + ';({channels:EXTENDED_MODEL_CHANNELS,registry:STATIC_MODEL_REGISTRY})')
  const {packed} = verify(value)
  const packageRoot = path.join(root,'apps/miniprogram/miniprogram')
  const dataFile = path.join(packageRoot,'utils/static-model-catalog-data.js')
  function bytes(dir) {
    return fs.readdirSync(dir,{withFileTypes:true}).reduce((sum, entry) => {
      const file = path.join(dir,entry.name)
      return sum + (entry.isDirectory() ? bytes(file) : file === dataFile ? 0 : fs.statSync(file).size)
    },0)
  }
  const generated = '// Generated by scripts/sync-model-catalog.mjs. Do not edit by hand.\nmodule.exports = ' + JSON.stringify(packed) + '\n'
  const projected = bytes(packageRoot) + Buffer.byteLength(generated)
  assert.ok(projected < 1.5 * 1024 * 1024, `projected source package ${projected} bytes exceeds existing 1.5 MiB budget`)
})
